# Generated by Django 2.2.10 on 2021-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_auto_20211208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.TextField(blank=True, default='Enter your Address'),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(blank=True, default='Enter your Email', max_length=100),
        ),
    ]
